---
name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/reusable-checks.yaml

  build-and-push-image:
    name: Build and Push Image
    needs: [checks]
    uses: x-real-ip/github-actions/.github/workflows/build-and-push.yaml@v2
    with:
      push: true

  dispatch-update-manifest:
    name: Repository Dispatch to Update Manifest
    needs: [build-and-push-image]
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: x-real-ip/gitops
          event-type: update-manifest
          client-payload:
            '{"ref": "${{ github.ref }}", "repository": "${{
            github.repository}}", "registry": "ghcr.io", "sha": "${{ github.sha
            }}"}'
