---
name: Check releases

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-releases:
    uses: x-real-ip/github-actions/.github/workflows/new-release-issue.yaml@main
    strategy:
      matrix:
        include:
          - name: home-assistant
            type: release
            target: home-assistant/core
            bump: true
            bump_type: containerfile
            image: "ghcr.io/home-assistant/home-assistant"
    with:
      name: ${{ matrix.name }}
      target: ${{ matrix.target }}
      type: ${{ matrix.type }}
      bump: ${{ matrix.bump }}
      bump_type: ${{ matrix.bump_type }}
