---
name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checks:
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-checks.yaml
